# -*- coding: utf-8 -*-
"""QGSO TSP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtUkIlWVnU9FnsiO97ulcjfy1oeNo_o-
"""

!pip install -q qiskit qiskit-aer qiskit-optimization networkx matplotlib ortools folium

import random
import itertools
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
import folium

from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator
from qiskit_optimization import QuadraticProgram
from qiskit_optimization.converters import QuadraticProgramToQubo
from ortools.constraint_solver import pywrapcp, routing_enums_pb2

MASTER_SEED = 42
POPULATION_SIZE = 20
ITERATIONS = 50
MUTATION_RATE = 0.20
NUMBER_OF_EXPERIMENTS = 3

random.seed(MASTER_SEED)
np.random.seed(MASTER_SEED)

cities = [
    "Bhubaneswar",
    "Cuttack",
    "Puri",
    "Khordha",
    "Dhenkanal",
    "Jajpur",
    "Balasore",
    "Berhampur"
]

coordinates = np.array([
    [20.2961, 85.8245],
    [20.4625, 85.8830],
    [19.8135, 85.8312],
    [20.1827, 85.6160],
    [20.6600, 85.6000],
    [20.8500, 86.3333],
    [21.4942, 86.9316],
    [19.3150, 84.7941]
], dtype=float)

n = len(cities)

def haversine(lat1, lon1, lat2, lon2):
    R = 6371.0
    lat1 = np.radians(lat1)
    lat2 = np.radians(lat2)
    dlat = lat2 - lat1
    dlon = np.radians(lon2) - np.radians(lon1)

    a = (
        np.sin(dlat / 2) ** 2 +
        np.cos(lat1) *
        np.cos(lat2) *
        np.sin(dlon / 2) ** 2
    )

    return 2 * R * np.arctan2(
        np.sqrt(a),
        np.sqrt(1 - a)
    )

distance = np.zeros((n, n), dtype=float)

for i in range(n):
    for j in range(n):
        if i != j:
            distance[i][j] = haversine(
                coordinates[i][0],
                coordinates[i][1],
                coordinates[j][0],
                coordinates[j][1]
            )

def tour_length(tour, distance):
    return sum(
        distance[
            tour[i],
            tour[(i + 1) % len(tour)]
        ]
        for i in range(len(tour))
    )

def create_population(population_size, n):
    population = []

    for _ in range(population_size):
        tour = list(range(n))
        random.shuffle(tour)
        population.append(tour)

    return population

def calculate_masses(fitness):
    fitness = np.asarray(fitness, dtype=float)

    best = np.min(fitness)
    worst = np.max(fitness)

    if np.isclose(best, worst):
        return np.ones(len(fitness)) / len(fitness)

    masses = (worst - fitness) / (worst - best)
    total = np.sum(masses)

    if total <= 0:
        return np.ones(len(fitness)) / len(fitness)

    return masses / total

def move_towards(agent, attractor):
    new_agent = agent.copy()

    position = random.randrange(len(agent))
    target_city = attractor[position]
    current_position = new_agent.index(target_city)

    new_agent[position], new_agent[current_position] = (
        new_agent[current_position],
        new_agent[position]
    )

    return new_agent

def mutate(tour):
    new_tour = tour.copy()

    a, b = random.sample(range(len(new_tour)), 2)

    new_tour[a], new_tour[b] = (
        new_tour[b],
        new_tour[a]
    )

    return new_tour

def gravitational_search_tsp(
    distance,
    population_size=20,
    iterations=50,
    mutation_rate=0.20
):
    n = len(distance)
    population = create_population(population_size, n)

    best_tour = None
    best_distance = float("inf")
    convergence = []

    for iteration in range(iterations):

        fitness = [
            tour_length(tour, distance)
            for tour in population
        ]

        best_index = int(np.argmin(fitness))

        if fitness[best_index] < best_distance:
            best_distance = fitness[best_index]
            best_tour = population[best_index].copy()

        masses = calculate_masses(fitness)

        k = max(
            2,
            int(
                population_size *
                (1 - iteration / iterations)
            )
        )

        strongest = sorted(
            range(population_size),
            key=lambda i: fitness[i]
        )[:k]

        new_population = []

        for i in range(population_size):

            agent = population[i].copy()

            for j in strongest:

                if i == j:
                    continue

                if random.random() < masses[j]:
                    agent = move_towards(
                        agent,
                        population[j]
                    )

            if random.random() < mutation_rate:
                agent = mutate(agent)

            new_population.append(agent)

        population = new_population
        convergence.append(best_distance)

    return best_tour, best_distance, convergence

def create_mass_hamiltonian(mass):
    mass = float(np.clip(mass, 0.0, 1.0))
    theta = np.pi * mass

    return np.array([
        [np.cos(theta), np.sin(theta)],
        [np.sin(theta), -np.cos(theta)]
    ], dtype=complex)

def check_hermitian(matrix):
    return np.allclose(
        matrix,
        matrix.conj().T
    )

def create_unitary_operator(mass):
    mass = float(np.clip(mass, 0.0, 1.0))
    theta = np.pi * mass

    return np.array([
        [np.cos(theta), -np.sin(theta)],
        [np.sin(theta), np.cos(theta)]
    ], dtype=complex)

def check_unitary(matrix):
    identity = np.eye(matrix.shape[0])

    return np.allclose(
        matrix.conj().T @ matrix,
        identity
    )

simulator = AerSimulator(method="statevector")

def quantum_gravitational_measurement(masses):
    masses = np.asarray(masses, dtype=float)
    qubit_count = len(masses)

    qc = QuantumCircuit(
        qubit_count,
        qubit_count
    )

    for q, mass in enumerate(masses):

        mass = float(np.clip(mass, 0.0, 1.0))
        theta = np.pi * mass

        qc.ry(theta, q)
        qc.measure(q, q)

    result = simulator.run(
        qc,
        shots=1
    ).result()

    counts = result.get_counts()
    measured = next(iter(counts))[::-1]

    decisions = np.array(
        [int(bit) for bit in measured],
        dtype=int
    )

    return decisions, qc

def quantum_move_towards(
    agent,
    attractor,
    quantum_decision
):
    new_agent = agent.copy()

    if quantum_decision == 1:

        position = random.randrange(len(agent))
        target_city = attractor[position]
        current_position = new_agent.index(target_city)

        new_agent[position], new_agent[current_position] = (
            new_agent[current_position],
            new_agent[position]
        )

    return new_agent

def quantum_gravitational_search_tsp(
    distance,
    population_size=20,
    iterations=50,
    mutation_rate=0.20
):
    n = len(distance)

    population = create_population(
        population_size,
        n
    )

    best_tour = None
    best_distance = float("inf")
    convergence = []
    decision_history = []

    quantum_circuit_count = 0
    hermitian_valid = True
    unitary_valid = True

    for iteration in range(iterations):

        fitness = [
            tour_length(tour, distance)
            for tour in population
        ]

        best_index = int(np.argmin(fitness))

        if fitness[best_index] < best_distance:
            best_distance = fitness[best_index]
            best_tour = population[best_index].copy()

        masses = calculate_masses(fitness)

        for mass in masses:

            H = create_mass_hamiltonian(mass)
            U = create_unitary_operator(mass)

            hermitian_valid &= check_hermitian(H)
            unitary_valid &= check_unitary(U)

        decisions, circuit = quantum_gravitational_measurement(masses)

        quantum_circuit_count += 1
        decision_history.extend(decisions.tolist())

        k = max(
            2,
            int(
                population_size *
                (1 - iteration / iterations)
            )
        )

        strongest = sorted(
            range(population_size),
            key=lambda i: fitness[i]
        )[:k]

        new_population = []

        for i in range(population_size):

            agent = population[i].copy()
            quantum_decision = decisions[i]

            for j in strongest:

                if i == j:
                    continue

                gravitational_strength = masses[j]

                if quantum_decision == 1:

                    if random.random() < gravitational_strength:

                        agent = quantum_move_towards(
                            agent,
                            population[j],
                            quantum_decision
                        )

            if random.random() < mutation_rate:
                agent = mutate(agent)

            new_population.append(agent)

        population = new_population
        convergence.append(best_distance)

    return {
        "tour": best_tour,
        "distance": best_distance,
        "convergence": convergence,
        "decisions": decision_history,
        "hermitian": hermitian_valid,
        "unitary": unitary_valid,
        "quantum_circuits": quantum_circuit_count,
        "quantum_qubits": population_size
    }

qp = QuadraticProgram("QGSO_TSP")

for city in range(n):
    for position in range(n):
        qp.binary_var(
            name=f"x_{city}_{position}"
        )

quadratic = {}

for position in range(n):

    next_position = (position + 1) % n

    for city_i in range(n):

        for city_j in range(n):

            if city_i != city_j:

                quadratic[
                    (
                        f"x_{city_i}_{position}",
                        f"x_{city_j}_{next_position}"
                    )
                ] = distance[city_i, city_j]

for city in range(n):

    expression = {
        f"x_{city}_{position}": 1
        for position in range(n)
    }

    qp.linear_constraint(
        linear=expression,
        sense="==",
        rhs=1,
        name=f"city_{city}"
    )

for position in range(n):

    expression = {
        f"x_{city}_{position}": 1
        for city in range(n)
    }

    qp.linear_constraint(
        linear=expression,
        sense="==",
        rhs=1,
        name=f"position_{position}"
    )

qp.minimize(quadratic=quadratic)

converter = QuadraticProgramToQubo()
qubo = converter.convert(qp)

def exact_tsp(distance):
    cities_to_visit = list(range(1, len(distance)))

    best_tour = None
    best_distance = float("inf")

    for permutation in itertools.permutations(cities_to_visit):

        tour = [0] + list(permutation)
        d = tour_length(tour, distance)

        if d < best_distance:
            best_distance = d
            best_tour = tour.copy()

    return best_tour, best_distance

optimal_tour, optimal_distance = exact_tsp(distance)

random.seed(MASTER_SEED)
np.random.seed(MASTER_SEED)

gso_tour, gso_distance, gso_convergence = (
    gravitational_search_tsp(
        distance,
        POPULATION_SIZE,
        ITERATIONS,
        MUTATION_RATE
    )
)

random.seed(MASTER_SEED)
np.random.seed(MASTER_SEED)

qgso_result = quantum_gravitational_search_tsp(
    distance,
    POPULATION_SIZE,
    ITERATIONS,
    MUTATION_RATE
)

qgso_tour = qgso_result["tour"]
qgso_distance = qgso_result["distance"]
qgso_convergence = qgso_result["convergence"]

def solve_tsp_ortools(distance):

    n = len(distance)

    manager = pywrapcp.RoutingIndexManager(
        n,
        1,
        0
    )

    routing = pywrapcp.RoutingModel(manager)

    def distance_callback(from_index, to_index):

        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)

        return int(
            round(
                distance[from_node, to_node] * 1000
            )
        )

    callback_index = routing.RegisterTransitCallback(
        distance_callback
    )

    routing.SetArcCostEvaluatorOfAllVehicles(
        callback_index
    )

    search_parameters = (
        pywrapcp.DefaultRoutingSearchParameters()
    )

    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
    )

    search_parameters.local_search_metaheuristic = (
        routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH
    )

    search_parameters.time_limit.seconds = 5

    solution = routing.SolveWithParameters(
        search_parameters
    )

    if solution is None:
        return None, None

    tour = []
    index = routing.Start(0)

    while not routing.IsEnd(index):

        tour.append(
            manager.IndexToNode(index)
        )

        index = solution.Value(
            routing.NextVar(index)
        )

    return tour, tour_length(tour, distance)

ortools_tour, ortools_distance = solve_tsp_ortools(distance)

decisions = np.asarray(
    qgso_result["decisions"]
)

gso_runs = []
qgso_runs = []

for experiment in range(NUMBER_OF_EXPERIMENTS):

    seed = MASTER_SEED + experiment + 1

    random.seed(seed)
    np.random.seed(seed)

    _, g_distance, _ = gravitational_search_tsp(
        distance,
        POPULATION_SIZE,
        ITERATIONS,
        MUTATION_RATE
    )

    random.seed(seed)
    np.random.seed(seed)

    q_result = quantum_gravitational_search_tsp(
        distance,
        POPULATION_SIZE,
        ITERATIONS,
        MUTATION_RATE
    )

    gso_runs.append(g_distance)
    qgso_runs.append(q_result["distance"])

gso_runs = np.asarray(gso_runs)
qgso_runs = np.asarray(qgso_runs)

print("GSO:", gso_tour, gso_distance)
print("QGSO:", qgso_tour, qgso_distance)
print("OR-Tools:", ortools_tour, ortools_distance)
print("Exact:", optimal_tour, optimal_distance)

plt.figure(figsize=(10, 6))

plt.plot(
    gso_convergence,
    linewidth=2,
    label="GSO"
)

plt.plot(
    qgso_convergence,
    linewidth=2,
    label="QGSO"
)

plt.axhline(
    optimal_distance,
    linestyle="--",
    linewidth=2,
    label="Exact optimum"
)

plt.xlabel("Iteration")
plt.ylabel("Best Tour Distance (km)")
plt.title("GSO vs QGSO Convergence")
plt.legend()
plt.grid(True)

plt.show()

plt.figure(figsize=(9, 6))

plt.bar(
    ["GSO", "QGSO", "OR-Tools", "Optimal"],
    [
        gso_distance,
        qgso_distance,
        ortools_distance,
        optimal_distance
    ]
)

plt.ylabel("Tour Distance (km)")
plt.title("GSO vs QGSO vs OR-Tools vs Exact TSP")
plt.grid(axis="y")

plt.show()

plt.figure(figsize=(9, 6))

plt.boxplot(
    [gso_runs, qgso_runs],
    tick_labels=["GSO", "QGSO"]
)

plt.ylabel("Tour Distance (km)")
plt.title("Multi-Run GSO vs QGSO")
plt.grid(axis="y")

plt.show()

sample_count = min(
    200,
    len(decisions)
)

plt.figure(figsize=(10, 6))

plt.step(
    range(sample_count),
    decisions[:sample_count],
    where="mid",
    linewidth=1.5
)

plt.xlabel("Quantum Measurement")
plt.ylabel("Quantum State")
plt.title("QGSO Quantum Measurement Decisions")

plt.yticks([0, 1])
plt.grid(True)

plt.show()

def create_route_map(tour, title):

    center_lat = coordinates[:, 0].mean()
    center_lon = coordinates[:, 1].mean()

    m = folium.Map(
        location=[center_lat, center_lon],
        zoom_start=8,
        tiles="OpenStreetMap"
    )

    closed_tour = tour + [tour[0]]

    for i in range(n):

        folium.Marker(
            location=[
                coordinates[i][0],
                coordinates[i][1]
            ],
            tooltip=f"{i}: {cities[i]}",
            popup=(
                f"<b>City {i}</b><br>"
                f"{cities[i]}<br>"
                f"Latitude: {coordinates[i][0]:.4f}<br>"
                f"Longitude: {coordinates[i][1]:.4f}"
            )
        ).add_to(m)

    route_coordinates = [
        [
            coordinates[city][0],
            coordinates[city][1]
        ]
        for city in closed_tour
    ]

    folium.PolyLine(
        locations=route_coordinates,
        weight=5,
        opacity=0.8,
        tooltip=title
    ).add_to(m)

    return m

display(
    create_route_map(
        gso_tour,
        "GSO TSP Route"
    )
)

display(
    create_route_map(
        qgso_tour,
        "QGSO TSP Route"
    )
)

display(
    create_route_map(
        ortools_tour,
        "Google OR-Tools TSP Route"
    )
)

display(
    create_route_map(
        optimal_tour,
        "Exact TSP Route"
    )
)

print("End")